server:
  ip: 0.0.0.0
  port: 8000
  http_port: 8003
  vision_explain: http://192.144.232.160:8003/mcp/vision/explain

manager-api:
  url: http://xiaozhi-esp32-server-web:8002/xiaozhi
  secret: b965c4f6-de09-45a5-8c43-cfbb0a312bd1

prompt_template: agent-base-prompt.txt
